server:
  http:
    addr: 0.0.0.0:8001
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:wang111000@tcp(127.0.0.1:3306)/machine?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_key: 7d25c9b8d23acb6bc6565270495ed7a0 # md5 dhbmachine